# Facebook (FB):

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import quandl

import iex as IEX

from iexfinance import Stock
from iexfinance import get_historical_data
from iexfinance import get_stats_intraday

from datetime import datetime

quandl.ApiConfig.api_key = "9tQnPMV9zakeCm4K6S5X"

In [2]:
! ls data

EOD-datasets-codes.csv google_iex.csv         twitter_iex.csv
facebook_iex.csv       ibm_iex.csv            weibo_iex.csv

## Importing Stock History - Facebook:

- **From Quadle**

In [28]:
df = pd.read_csv('data/facebook_quandle.csv')
df.head()

,Date,WIKI/FB - Open,WIKI/FB - High,WIKI/FB - Low,WIKI/FB - Close,WIKI/FB - Volume,WIKI/FB - Ex-Dividend,WIKI/FB - Split Ratio,WIKI/FB - Adj. Open,WIKI/FB - Adj. High,WIKI/FB - Adj. Low,WIKI/FB - Adj. Close,WIKI/FB - Adj. Volume
0,2012-05-18,42.05,45.00,38.00,38.2318,573576400.0,0.0,1.0,42.05,45.00,38.00,38.2318,573576400.0
1,2012-05-21,36.53,36.66,33.00,34.0300,168192700.0,0.0,1.0,36.53,36.66,33.00,34.0300,168192700.0
2,2012-05-22,32.61,33.59,30.94,31.0000,101786600.0,0.0,1.0,32.61,33.59,30.94,31.0000,101786600.0
3,2012-05-23,31.37,32.50,31.36,32.0000,73600000.0,0.0,1.0,31.37,32.50,31.36,32.0000,73600000.0
4,2012-05-24,32.95,33.21,31.77,33.0300,50237200.0,0.0,1.0,32.95,33.21,31.77,33.0300,50237200.0

-------

## Querying IEX for Facebook's Stock:

In [30]:
fb = Stock('FB')

In [15]:
print('Current Price:', fb.get_price())
print('06/15/2018 Opening Price:', fb.get_open())
print('06/15/2018 Closing Price:', fb.get_close())

Current Price: 195.85
06/15/2018 Opening Price: 195.79
06/15/2018 Closing Price: 195.85

## Historical Data from IEX:

In [42]:
start = datetime(2013, 1, 1) ## 5 year limit:
end = datetime(2018, 6, 15) ## Today's Date

fb_df = get_historical_data("FB", start=start, end=end, output_format='pandas')
fb_df.head(10)

             open    high    low   close    volume
date
2013-06-17  23.91  24.250  23.75  24.022  33603061
2013-06-18  24.09  24.690  24.08  24.210  36672094
2013-06-19  24.20  25.190  24.10  24.309  31741274
2013-06-20  24.28  24.745  23.65  23.900  42737997
2013-06-21  24.59  24.700  24.05  24.530  45807968
2013-06-24  23.95  24.110  23.38  23.935  40593692
2013-06-25  24.14  24.430  24.04  24.250  24711324
2013-06-26  24.51  24.650  23.99  24.160  29869415
2013-06-27  24.24  24.840  24.21  24.660  34654256
2013-06-28  24.68  24.980  24.42  24.880  96755618

## Financial Statement:

In [21]:
iex = IEX.Stock()
financials = iex.get_financials('FB')
financials.T

                                  0            1            2            3
cashChange               3970000000    835000000    882000000   -920000000
cashFlow                 7860000000   7671000000   6127000000   5360000000
costOfRevenue            1927000000   1611000000   1448000000   1237000000
currentAssets           50412000000  48563000000  44203000000  40804000000
currentCash             12210000000   8079000000   7201000000   6252000000
currentDebt                    None         None         None         None
grossProfit             10039000000  11361000000   8880000000   8084000000
netIncome                4988000000   4269000000   4707000000   3894000000
operatingExpense         4590000000   4009000000   3758000000   3683000000
operatingGainsLosses           None         None         None         None
operatingIncome          5449000000   7352000000   5122000000   4401000000
operatingRevenue        11795000000  12779000000  10142000000   9164000000
reportDate               2018-03-31   2017-12-31   2017-09-30   2017-06-30
researchAndDevelopment   2238000000   1949000000   2052000000   1919000000
shareholderEquity       77620000000  74347000000  71208000000  66481000000
totalAssets             88945000000  84524000000  78998000000  73843000000
totalCash               43956000000  41711000000  38289000000  35452000000
totalDebt                      None         None         None         None
totalLiabilities               None         None         None         None
totalRevenue            11966000000  12972000000  10328000000   9321000000

## Earnings:

https://www.wallstreetmojo.com/revenue-vs-earnings/

In [22]:
earnings = iex.get_earnings('FB')
earnings.T

                                 0           1           2           3
EPSReportDate           2018-04-25  2018-01-31  2017-11-01  2017-07-26
EPSSurpriseDollar             0.33        0.24        0.31        0.19
actualEPS                     1.69         2.2        1.59        1.32
announceTime                   AMC         AMC         AMC         AMC
consensusEPS                  1.36        1.96        1.28        1.13
estimatedChangePercent    0.307692    0.580645    0.454545    0.486842
estimatedEPS                  1.36        1.96        1.28        1.13
fiscalEndDate           2018-03-31  2017-12-31  2017-09-30  2017-06-30
fiscalPeriod               Q1 2018     Q4 2017     Q3 2017     Q2 2017
numberOfEstimates               14          14          18          14
symbolId                      2408        2408        2408        2408
yearAgo                       1.04        1.24        0.88        0.76
yearAgoChangePercent         0.625    0.774194    0.806818    0.736842

In [31]:
fb_chart = iex.get_chart('FB', chart_range='5y')
print(fb_chart.shape)
fb_chart.head()

(1260, 12)

,change,changeOverTime,changePercent,close,date,high,label,low,open,unadjustedVolume,volume,vwap
0,0.392,0.000000,1.659,24.022,2013-06-17,24.250,"Jun 17, 13",23.75,23.91,33603061,33603061,24.0331
1,0.188,0.007826,0.783,24.210,2013-06-18,24.690,"Jun 18, 13",24.08,24.09,36672094,36672094,24.4482
2,0.099,0.011947,0.409,24.309,2013-06-19,25.190,"Jun 19, 13",24.10,24.20,31741274,31741274,24.3771
3,-0.409,-0.005079,-1.683,23.900,2013-06-20,24.745,"Jun 20, 13",23.65,24.28,42737997,42737997,24.0846
4,0.630,0.021147,2.636,24.530,2013-06-21,24.700,"Jun 21, 13",24.05,24.59,45807968,45807968,24.3850

## Getting a Quote:

In [32]:
print(iex.get_delayed_quote('FB'))
iex.get_quote('FB')

{'symbol': 'FB', 'delayedPrice': 195.85, 'high': 197.07, 'low': 194.64, 'delayedSize': 3370373, 'delayedPriceTime': 1529092800254, 'processedTime': 1529093701006}

{'symbol': 'FB',
 'companyName': 'Facebook Inc.',
 'primaryExchange': 'Nasdaq Global Select',
 'sector': 'Technology',
 'calculationPrice': 'close',
 'open': 195.79,
 'openTime': 1529069400436,
 'close': 195.85,
 'closeTime': 1529092800254,
 'high': 197.07,
 'low': 194.64,
 'latestPrice': 195.85,
 'latestSource': 'Close',
 'latestTime': 'June 15, 2018',
 'latestUpdate': 1529092800254,
 'latestVolume': 21828956,
 'iexRealtimePrice': 195.81,
 'iexRealtimeSize': 200,
 'iexLastUpdated': 1529093199593,
 'delayedPrice': 195.85,
 'delayedPriceTime': 1529092800254,
 'extendedPrice': 195.55,
 'extendedChange': -0.3,
 'extendedChangePercent': -0.00153,
 'extendedPriceTime': 1529096364789,
 'previousClose': 196.81,
 'change': -0.96,
 'changePercent': -0.00488,
 'iexMarketPercent': 0.02231,
 'iexVolume': 487004,
 'avgTotalVolume': 17086712,
 'iexBidPrice': 0,
 'iexBidSize': 0,
 'iexAskPrice': 0,
 'iexAskSize': 0,
 'marketCap': 566912844446,
 'peRatio': 28.8,
 'week52High': 197.28,
 'week52Low': 146.3747,
 'ytdChange': 0.0799507794069012}

In [25]:
iex.get_effective_spread('FB')

,effectiveQuoted,effectiveSpread,priceImprovement,venue,venueName,volume
0,0.848357,0.020314,0.002168,XBOS,Nasdaq BX,6390348
1,0.844462,0.018434,0.002239,XPHL,Nasdaq PSX,1437527
2,0.685459,0.017116,0.005011,XCHI,CHX,18329
3,0.790962,0.016867,0.002957,BATY,Cboe BYX,4638442
4,0.944053,0.016295,0.000571,XCIS,NYSE National,12622
5,0.932095,0.015893,0.000930,ARCX,NYSE Arca,17533613
6,0.735897,0.015328,0.003665,BATS,Cboe BZX,19020826
7,0.775155,0.015027,0.003017,XNGS,Nasdaq,69682267
8,0.853200,0.013792,0.001894,XASE,NYSE American,355038
9,0.770578,0.013771,0.003040,EDGA,Cboe EDGA,2785289
10,0.766421,0.013292,0.003011,EDGX,Cboe EDGX,23627536
11,0.863186,0.013210,0.001632,XNYS,NYSE,1488778
12,0.475663,0.009310,0.006553,IEXG,IEX,10037689

## Stats:

In [26]:
iex.get_stats('FB').T

                                 0
EBITDA                 19626000000
EPSSurpriseDollar             None
EPSSurprisePercent         24.2647
beta                      0.848888
cash                  115452000000
companyName          Facebook Inc.
consensusEPS                  1.36
day200MovingAvg            177.043
day30ChangePercent        0.108941
day50MovingAvg             179.128
day5ChangePercent        0.0225018
debt                             0
dividendRate                     0
dividendYield                    0
exDividendDate                   0
float                   2889341923
grossProfit            28325000000
insiderPercent                None
institutionPercent            53.5
latestEPS                        0
latestEPSDate           2017-12-31
marketcap             566912844446
month1ChangePercent      0.0625543
month3ChangePercent      0.0652127
month6ChangePercent      0.0869686
numberOfEstimates               14
peRatioHigh                      0
peRatioLow                       0
priceToBook                   None
priceToSales               12.9829
profitMargin                 40.67
returnOnAssets               21.42
returnOnCapital               None
returnOnEquity               24.13
revenue                32621000000
revenuePerEmployee         1175871
revenuePerShare                 11
sharesOutstanding       2894627748
shortDate               2018-05-31
shortInterest             27722131
shortRatio                 1.55195
symbol                          FB
ttmEPS                         6.8
week52change                30.741
week52high                  197.28
week52low                    147.8
year1ChangePercent         0.30741
year2ChangePercent        0.708988
year5ChangePercent         7.15294
ytdChangePercent         0.0795392