# JP Morgan (JPM):

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import quandl

import iex as IEX

from iexfinance import Stock
from iexfinance import get_historical_data
from iexfinance import get_stats_intraday

from datetime import datetime

quandl.ApiConfig.api_key = "9tQnPMV9zakeCm4K6S5X"

In [2]:
! ls data

EOD-datasets-codes.csv facebook_quandle.csv   jpm_quandle.csv
apple_quandle.csv      google_quandle.csv     microsoft_quandle.csv
blackrock_quandle.csv  gs_quandle.csv         moodys_quandle.csv
dow_quandle.csv        ibm_quandle.csv        twitter_quandle.csv

## Importing Stock History - JP Morgan:

- **From Quadle**

In [3]:
df = pd.read_csv('data/jpm_quandle.csv')
df.head()

,Date,WIKI/JPM - Open,WIKI/JPM - High,WIKI/JPM - Low,WIKI/JPM - Close,WIKI/JPM - Volume,WIKI/JPM - Ex-Dividend,WIKI/JPM - Split Ratio,WIKI/JPM - Adj. Open,WIKI/JPM - Adj. High,WIKI/JPM - Adj. Low,WIKI/JPM - Adj. Close,WIKI/JPM - Adj. Volume
0,1983-12-30,44.00,44.50,43.50,44.00,47000.0,0.0,1.0,3.074327,3.109262,3.039391,3.074327,211500.0
1,1984-01-03,43.94,44.25,43.62,44.00,85667.0,0.0,1.0,3.070135,3.091795,3.047776,3.074327,385501.5
2,1984-01-04,44.84,45.87,44.25,45.87,65000.0,0.0,1.0,3.133019,3.204986,3.091795,3.204986,292500.0
3,1984-01-05,46.81,47.38,46.25,47.38,76467.0,0.0,1.0,3.270665,3.310491,3.231537,3.310491,344101.5
4,1984-01-06,46.88,47.38,46.38,46.88,43200.0,0.0,1.0,3.275556,3.310491,3.240620,3.275556,194400.0

-------

## Querying IEX for Apple's Stock:

In [4]:
jp_morgan = Stock('JPM')

In [5]:
print('Current Price:', jp_morgan.get_price())
print('06/15/2018 Opening Price:', jp_morgan.get_open())
print('06/15/2018 Closing Price:', jp_morgan.get_close())

Current Price: 107.9
06/15/2018 Opening Price: 107.9
06/15/2018 Closing Price: 107.9

## Historical Data from IEX:

In [8]:
start = datetime(2013, 1, 1) ## 5 year limit:
end = datetime(2018, 6, 15) ## Today's Date

jpm_df = get_historical_data("JPM", start=start, end=end, output_format='pandas')
jpm_df.head(10)

               open     high      low    close    volume
date
2013-06-17  47.1648  47.6522  47.0242  47.2965  16855353
2013-06-18  47.4546  47.6654  47.1823  47.5249  13253408
2013-06-19  47.4195  47.8762  47.0067  47.0330  20838070
2013-06-20  46.6202  46.7080  45.9088  46.0932  31862273
2013-06-21  46.5148  46.5324  45.3994  45.6365  44414895
2013-06-24  44.6880  45.1886  44.0117  44.7231  30555014
2013-06-25  45.2413  46.1674  45.2413  45.7419  20899419
2013-06-26  46.2425  46.3743  45.5645  46.1108  19331616
2013-06-27  46.5763  46.9803  46.4446  46.6817  17094217
2013-06-28  46.6553  46.6641  46.1811  46.3655  18262487

## Financial Statement:

In [9]:
iex = IEX.Stock()
financials = iex.get_financials('JPM')
financials.T

,0,1,2,3
cashChange,-19541000000,3833000000,217000000,-70350000000
cashFlow,-35109000000,13537000000,-3014000000,9535000000
costOfRevenue,None,None,None,None
currentAssets,None,None,None,None
currentCash,414812000000,25827000000,21994000000,21781000000
currentDebt,27486000000,50647000000,24248000000,22207000000
grossProfit,None,None,None,None
netIncome,8712000000,4232000000,6732000000,7029000000
operatingExpense,None,None,None,None
operatingGainsLosses,None,None,None,None
operatingIncome,None,None,None,None
operatingRevenue,None,None,None,None
reportDate,2018-03-31,2017-12-31,2017-09-30,2017-06-30
researchAndDevelopment,None,None,None,None
shareholderEquity,256201000000,255693000000,258382000000,258483000000
totalAssets,2609785000000,2533600000000,2563074000000,2563174000000
totalCash,None,None,None,None
totalDebt,301935000000,308266000000,342549000000,346116000000
totalLiabilities,None,None,None,None
totalRevenue,27907000000,24153000000,25326000000,25470000000

## Earnings:

https://www.wallstreetmojo.com/revenue-vs-earnings/

In [10]:
earnings = iex.get_earnings('JPM')
earnings.T

                                 0           1           2           3
EPSReportDate           2018-04-13  2018-01-12  2017-10-12  2017-07-14
EPSSurpriseDollar             0.09        0.07        0.09        0.25
actualEPS                     2.37        1.76        1.76        1.82
announceTime                   BTO         BTO         BTO         BTO
consensusEPS                  2.28        1.69        1.67        1.57
estimatedChangePercent    0.381818  -0.0116959    0.056962   0.0129032
estimatedEPS                  2.28        1.69        1.67        1.57
fiscalEndDate           2018-03-31  2017-12-31  2017-09-30  2017-06-30
fiscalPeriod               Q1 2018     Q4 2017     Q3 2017     Q2 2017
numberOfEstimates                8           8           8           7
symbolId                      3821        3821        3821        3821
yearAgo                       1.65        1.71        1.58        1.55
yearAgoChangePercent      0.436364   0.0292398    0.113924    0.174194

In [11]:
iex.get_chart('JPM', chart_range='5y')

,change,changeOverTime,changePercent,close,date,high,label,low,open,unadjustedVolume,volume,vwap
0,0.632377,0.000000,1.355,47.2965,2013-06-17,47.6522,"Jun 17, 13",47.0242,47.1648,16855353,16855353,47.3666
1,0.228356,0.004829,0.483,47.5249,2013-06-18,47.6654,"Jun 18, 13",47.1823,47.4546,13253408,13253408,47.4429
2,-0.491847,-0.005571,-1.035,47.0330,2013-06-19,47.8762,"Jun 19, 13",47.0067,47.4195,20838070,20838070,47.3339
3,-0.939781,-0.025442,-1.998,46.0932,2013-06-20,46.7080,"Jun 20, 13",45.9088,46.6202,31862273,31862273,46.2417
4,-0.456716,-0.035098,-0.991,45.6365,2013-06-21,46.5324,"Jun 21, 13",45.3994,46.5148,44414895,44414895,45.8360
5,-0.913433,-0.054410,-2.002,44.7231,2013-06-24,45.1886,"Jun 24, 13",44.0117,44.6880,30555014,30555014,44.6134
6,1.018800,-0.032869,2.278,45.7419,2013-06-25,46.1674,"Jun 25, 13",45.2413,45.2413,20899419,20899419,45.6535
7,0.368886,-0.025070,0.806,46.1108,2013-06-26,46.3743,"Jun 26, 13",45.5645,46.2425,19331616,19331616,46.0319
8,0.570896,-0.012999,1.238,46.6817,2013-06-27,46.9803,"Jun 27, 13",46.4446,46.5763,17094217,17094217,46.7725
9,-0.316190,-0.019684,-0.677,46.3655,2013-06-28,46.6641,"Jun 28, 13",46.1811,46.6553,18262487,18262487,46.4255
10,0.072677,-0.018147,0.157,46.4382,2013-07-01,47.4467,"Jul 1, 13",46.3851,47.0840,23513028,23513028,46.9704
11,0.274261,-0.012350,0.591,46.7124,2013-07-02,47.3583,"Jul 2, 13",46.1108,46.5090,23939764,23939764,46.8431
12,-0.026544,-0.012910,-0.057,46.6859,2013-07-03,46.7213,"Jul 3, 13",46.1905,46.2789,10443381,10443381,46.4938
13,1.079300,0.009910,2.312,47.7652,2013-07-05,47.7741,"Jul 5, 13",46.9867,47.2079,17070738,17070738,47.4741
14,0.628141,0.023192,1.315,48.3934,2013-07-08,48.5792,"Jul 8, 13",47.8183,48.2518,21787090,21787090,48.2825
15,0.168095,0.026746,0.347,48.5615,2013-07-09,48.8092,"Jul 9, 13",47.9422,48.7207,20510215,20510215,48.4612
16,-0.053083,0.025623,-0.109,48.5084,2013-07-10,48.7915,"Jul 10, 13",48.1634,48.4553,16931388,16931388,48.4381
17,0.274260,0.031423,0.565,48.7827,2013-07-11,49.4285,"Jul 11, 13",48.2607,49.4019,21295126,21295126,48.7198
18,-0.150402,0.028241,-0.308,48.6322,2013-07-12,49.4108,"Jul 12, 13",48.4376,49.1100,32526194,32526194,48.8664
19,-0.070775,0.026746,-0.146,48.5615,2013-07-15,49.1011,"Jul 15, 13",48.3049,49.0923,28296290,28296290,48.5063
20,0.106163,0.028989,0.219,48.6676,2013-07-16,49.0215,"Jul 16, 13",48.4642,48.5703,19224290,19224290,48.7341
21,0.230023,0.033855,0.473,48.8977,2013-07-17,49.1719,"Jul 17, 13",48.5172,48.7030,19166250,19166250,48.8939
22,0.973177,0.054429,1.990,49.8708,2013-07-18,50.0124,"Jul 18, 13",49.0923,49.1100,24562658,24562658,49.6511
23,-0.185789,0.050501,-0.373,49.6850,2013-07-19,50.0345,"Jul 19, 13",49.4639,49.9947,17760823,17760823,49.6910
24,0.353883,0.057983,0.712,50.0389,2013-07-22,50.1362,"Jul 22, 13",49.4993,49.6939,16001777,16001777,49.9402
25,0.097315,0.060040,0.194,50.1362,2013-07-23,50.3309,"Jul 23, 13",49.9637,50.1805,10577746,10577746,50.1425
26,-0.035386,0.059294,-0.071,50.1009,2013-07-24,50.3663,"Jul 24, 13",49.8797,50.3574,16664911,16664911,50.0653
27,-0.115010,0.056860,-0.230,49.9858,2013-07-25,49.9858,"Jul 25, 13",49.4462,49.9416,13860446,13860446,49.7456
28,-0.398119,0.048443,-0.796,49.5877,2013-07-26,49.7381,"Jul 26, 13",49.1896,49.5966,16765035,16765035,49.4979
29,-0.318494,0.041709,-0.642,49.2692,2013-07-29,49.5435,"Jul 29, 13",48.9950,49.5258,10053378,10053378,49.2238
...,...,...,...,...,...,...,...,...,...,...,...,...
1230,1.190000,1.292559,1.110,108.4300,2018-05-04,108.7400,"May 4, 18",105.9800,106.4300,11967906,11967906,107.8405
1231,0.940000,1.312433,0.867,109.3700,2018-05-07,109.6800,"May 7, 18",108.3600,108.7600,9356721,9356721,109.0803
1232,1.620000,1.346685,1.481,110.9900,2018-05-08,111.3400,"May 8, 18",109.2800,109.5300,12543228,12543228,110.6274
1233,2.420000,1.397852,2.180,113.4100,2018-05-09,113.6400,"May 9, 18",111.0300,111.4400,11368094,11368094,112.7312
1234,0.880000,1.416458,0.776,114.2900,2018-05-10,114.4400,"May 10, 18",112.7500,113.1900,9159709,9159709,113.9139
1235,-0.430000,1.407366,-0.376,113.8600,2018-05-11,114.7300,"May 11, 18",113.6700,114.4900,10253045,10253045,114.0472
1236,0.040000,1.408212,0.035,113.9000,2018-05-14,114.7000,"May 14, 18",113.7400,114.1100,8710654,8710654,114.0966
1237,-0.870000,1.389817,-0.764,113.0300,2018-05-15,113.9100,May 15,112.5700,113.9100,11536212,11536212,113.0974
1238,0.310000,1.396372,0.274,113.3400,2018-05-16,113.6900,May 16,112.6300,112.8900,7571089,7571089,113.2805
1239,-0.380000,1.388337,-0.335,112.9600,2018-05-17,113.4100,May 17,112.2000,113.2000,8617204,8617204,112.9367
1240,-1.830000,1.349645,-1.620,111.1300,2018-05-18,112.8000,May 18,110.8400,112.7500,11806349,11806349,111.5271
1241,1.020000,1.371211,0.918,112.1500,2018-05-21,112.5400,May 21,111.9200,112.0500,9441931,9441931,112.2348
1242,0.860000,1.389395,0.767,113.0100,2018-05-22,114.2852,May 22,112.2900,112.3500,11507550,11507550,113.4725
1243,-0.520000,1.378400,-0.460,112.4900,2018-05-23,112.7700,May 23,111.1200,112.5100,11453916,11453916,112.0229
1244,-1.260000,1.351760,-1.120,111.2300,2018-05-24,112.1500,May 24,110.1150,112.1400,14084769,14084769,110.9996
1245,-0.570000,1.339708,-0.512,110.6600,2018-05-25,111.0800,May 25,110.1950,110.4600,8283548,8283548,110.6180
1246,-4.730000,1.239701,-4.274,105.9300,2018-05-29,109.2000,May 29,104.9550,109.1800,30643840,30643840,106.4579
1247,2.420000,1.290867,2.285,108.3500,2018-05-30,108.6000,May 30,106.6500,107.6400,17490845,17490845,107.7951
1248,-1.340000,1.262535,-1.237,107.0100,2018-05-31,108.1900,May 31,106.4200,107.9500,19808203,19808203,107.1087
1249,1.390000,1.291924,1.299,108.4000,2018-06-01,108.9400,Jun 1,107.8000,108.3400,13594185,13594185,108.4085
1250,0.050000,1.292982,0.046,108.4500,2018-06-04,109.2550,Jun 4,108.2700,108.9900,9415437,9415437,108.5931
1251,-0.610000,1.280084,-0.562,107.8400,2018-06-05,108.3100,Jun 5,107.0700,108.2400,10415231,10415231,107.7166
1252,2.520000,1.333365,2.337,110.3600,2018-06-06,110.7400,Jun 6,108.4800,108.6600,15453563,15453563,110.0619
1253,0.440000,1.342668,0.399,110.8000,2018-06-07,111.5000,Jun 7,110.0250,111.1800,13444427,13444427,110.9020
1254,0.310000,1.349222,0.280,111.1100,2018-06-08,111.1400,Jun 8,110.0600,110.6200,10383168,10383168,110.7810
1255,-0.280000,1.343302,-0.252,110.8300,2018-06-11,111.9100,Jun 11,110.7700,111.1200,12642897,12642897,111.2449
1256,-0.640000,1.329771,-0.577,110.1900,2018-06-12,111.5300,Jun 12,109.5200,111.1400,15294082,15294082,110.4581
1257,-0.220000,1.325119,-0.200,109.9700,2018-06-13,111.4450,Jun 13,109.5800,110.4600,14979749,14979749,110.3076
1258,-1.940000,1.284101,-1.764,108.0300,2018-06-14,110.3600,Jun 14,107.7800,110.2800,20487343,20487343,108.3338
1259,-0.130000,1.281353,-0.120,107.9000,2018-06-15,108.3800,Jun 15,106.2700,107.8000,26028572,26028572,107.6304

## Getting a Quote:

In [12]:
print(iex.get_delayed_quote('JPM'))
iex.get_quote('JPM')

{'symbol': 'JPM', 'delayedPrice': 107.9, 'high': 108.38, 'low': 106.27, 'delayedSize': 6743663, 'delayedPriceTime': 1529092813015, 'processedTime': 1529093713509}

{'symbol': 'JPM',
 'companyName': 'JP Morgan Chase & Co.',
 'primaryExchange': 'New York Stock Exchange',
 'sector': 'Financial Services',
 'calculationPrice': 'close',
 'open': 107.9,
 'openTime': 1529069408152,
 'close': 107.9,
 'closeTime': 1529092813015,
 'high': 108.38,
 'low': 106.27,
 'latestPrice': 107.9,
 'latestSource': 'Close',
 'latestTime': 'June 15, 2018',
 'latestUpdate': 1529092813015,
 'latestVolume': 25805943,
 'iexRealtimePrice': 107.865,
 'iexRealtimeSize': 62,
 'iexLastUpdated': 1529092796650,
 'delayedPrice': 107.9,
 'delayedPriceTime': 1529092813015,
 'extendedPrice': 107.92,
 'extendedChange': 0.02,
 'extendedChangePercent': 0.00019,
 'extendedPriceTime': 1529096297637,
 'previousClose': 108.03,
 'change': -0.13,
 'changePercent': -0.0012,
 'iexMarketPercent': 0.0212,
 'iexVolume': 547086,
 'avgTotalVolume': 12893314,
 'iexBidPrice': 0,
 'iexBidSize': 0,
 'iexAskPrice': 0,
 'iexAskSize': 0,
 'marketCap': 367375429884,
 'peRatio': 13.99,
 'week52High': 119.33,
 'week52Low': 86.015,
 'ytdChange': 0.009854873802981447}

In [13]:
iex.get_effective_spread('JPM')

,effectiveQuoted,effectiveSpread,priceImprovement,venue,venueName,volume
0,0.842024,0.010334,0.001699,XCHI,CHX,8592
1,0.919692,0.010253,0.000543,BATY,Cboe BYX,3949609
2,0.940314,0.010165,0.000489,XBOS,Nasdaq BX,6235200
3,0.934248,0.010035,0.000581,EDGA,Cboe EDGA,3551775
4,0.892743,0.009715,0.001049,ARCX,NYSE Arca,14036190
5,0.929354,0.009647,0.000706,XCIS,NYSE National,2831
6,0.885636,0.009548,0.001116,EDGX,Cboe EDGX,15678661
7,0.874870,0.009399,0.001322,XPHL,Nasdaq PSX,1458708
8,0.858130,0.009393,0.001280,XNYS,NYSE,37334269
9,0.837943,0.009132,0.001484,BATS,Cboe BZX,21729006
10,0.812411,0.008686,0.001739,XNGS,Nasdaq,32049952
11,0.781370,0.008244,0.001984,XASE,NYSE American,527912
12,0.664102,0.007278,0.002265,IEXG,IEX,5066547

## Stats:

In [14]:
iex.get_stats('JPM').T

                                         0
EBITDA                                   0
EPSSurpriseDollar                     None
EPSSurprisePercent                  3.9474
beta                               1.18796
cash                                     0
companyName          JP Morgan Chase & Co.
consensusEPS                          2.28
day200MovingAvg                    105.668
day30ChangePercent             -0.00488795
day50MovingAvg                     110.444
day5ChangePercent               -0.0264369
debt                         1024547000000
dividendRate                          2.24
dividendYield                        2.076
exDividendDate       2018-07-05 00:00:00.0
float                           3387110403
grossProfit                              0
insiderPercent                        None
institutionPercent                    64.8
latestEPS                             6.32
latestEPSDate                   2017-12-31
marketcap                     367375429884
month1ChangePercent             -0.0453862
month3ChangePercent             -0.0589454
month6ChangePercent              0.0270586
numberOfEstimates                        8
peRatioHigh                           16.4
peRatioLow                               0
priceToBook                            1.6
priceToSales                       3.10301
profitMargin                         22.14
returnOnAssets                        0.89
returnOnCapital                       None
returnOnEquity                       10.01
revenue                        74949000000
revenuePerEmployee                  295416
revenuePerShare                         22
sharesOutstanding               3404776922
shortDate                       2018-05-31
shortInterest                     24588032
shortRatio                         1.96221
symbol                                 JPM
ttmEPS                                7.71
week52change                       27.3563
week52high                          119.33
week52low                            86.61
year1ChangePercent                0.273564
year2ChangePercent                0.826547
year5ChangePercent                 1.28135
ytdChangePercent                 0.0098382