# Microsoft (MSFT):

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import quandl

import iex as IEX

from iexfinance import Stock
from iexfinance import get_historical_data
from iexfinance import get_stats_intraday

from datetime import datetime

quandl.ApiConfig.api_key = "9tQnPMV9zakeCm4K6S5X"

In [3]:
! ls data

EOD-datasets-codes.csv facebook_quandle.csv   jpm_quandle.csv
apple_quandle.csv      google_quandle.csv     microsoft_quandle.csv
blackrock_quandle.csv  gs_quandle.csv         moodys_quandle.csv
dow_quandle.csv        ibm_quandle.csv        twitter_quandle.csv

## Importing Stock History - Microsoft:

- **From Quadle**

In [4]:
df = pd.read_csv('data/microsoft_quandle.csv')
df.head()

,Date,WIKI/MSFT - Open,WIKI/MSFT - High,WIKI/MSFT - Low,WIKI/MSFT - Close,WIKI/MSFT - Volume,WIKI/MSFT - Ex-Dividend,WIKI/MSFT - Split Ratio,WIKI/MSFT - Adj. Open,WIKI/MSFT - Adj. High,WIKI/MSFT - Adj. Low,WIKI/MSFT - Adj. Close,WIKI/MSFT - Adj. Volume
0,1986-03-13,25.50,29.25,25.5,28.00,3582600.0,0.0,1.0,0.058941,0.067609,0.058941,0.064720,1.031789e+09
1,1986-03-14,28.00,29.50,28.0,29.00,1070000.0,0.0,1.0,0.064720,0.068187,0.064720,0.067031,3.081600e+08
2,1986-03-17,29.00,29.75,29.0,29.50,462400.0,0.0,1.0,0.067031,0.068765,0.067031,0.068187,1.331712e+08
3,1986-03-18,29.50,29.75,28.5,28.75,235300.0,0.0,1.0,0.068187,0.068765,0.065876,0.066454,6.776640e+07
4,1986-03-19,28.75,29.00,28.0,28.25,166300.0,0.0,1.0,0.066454,0.067031,0.064720,0.065298,4.789440e+07

-------

## Querying IEX for Microsoft's Stock:

In [5]:
msft = Stock('MSFT')

In [6]:
print('Current Price:', msft.get_price())
print('06/15/2018 Opening Price:', msft.get_open())
print('06/15/2018 Closing Price:', msft.get_close())

Current Price: 100.13
06/15/2018 Opening Price: 101.52
06/15/2018 Closing Price: 100.13

## Historical Data from IEX:

In [7]:
start = datetime(2013, 1, 1) ## 5 year limit:
end = datetime(2018, 6, 15) ## Today's Date

msft_df = get_historical_data("MSFT", start=start, end=end, output_format='pandas')
msft_df.head(10)

               open     high      low    close    volume
date
2013-06-17  30.5644  30.9785  30.5115  30.8375  49670032
2013-06-18  30.8111  30.9873  30.7450  30.8199  28614869
2013-06-19  30.8023  30.9168  30.4763  30.4763  30816008
2013-06-20  30.1855  30.2472  29.4013  29.5071  54493643
2013-06-21  29.6569  29.7185  29.1194  29.3088  85337340
2013-06-24  29.0225  30.1326  28.6965  29.7053  56108988
2013-06-25  30.0269  30.2912  29.4806  29.6657  44051085
2013-06-26  30.0621  30.3793  29.8573  30.2648  48665592
2013-06-27  30.4146  30.6437  30.3970  30.5027  28993042
2013-06-28  30.2912  30.6525  30.2560  30.4366  65545445

## Financial Statement:

In [8]:
iex = IEX.Stock()
financials = iex.get_financials('MSFT')
financials.T

                                   0             1             2             3
cashChange               -3663000000    5992000000    -805000000     935000000
cashFlow                 12151000000    7875000000   12440000000   11005000000
costOfRevenue             9269000000   11064000000    8278000000    8456000000
currentAssets           156659000000  167633000000  161031000000  159851000000
currentCash               9221000000   12859000000    6884000000    7663000000
currentDebt               3677000000   15912000000    9220000000   10121000000
grossProfit              17550000000   17854000000   16260000000   10528000000
netIncome                 7424000000   -6302000000    6576000000    3784000000
operatingExpense          9258000000    9175000000    8552000000    9239000000
operatingGainsLosses      -347000000   -1749000000   -2329000000   12385000000
operatingIncome           8292000000    8679000000    7708000000    1289000000
operatingRevenue         26819000000   28918000000   24538000000   18984000000
reportDate                2018-03-31    2017-12-31    2017-09-30    2017-06-30
researchAndDevelopment    3715000000    3504000000    3574000000    3514000000
shareholderEquity        79239000000   78360000000   89647000000   72394000000
totalAssets             245497000000  256003000000  249097000000  241086000000
totalCash               132270000000  142780000000  138471000000  132981000000
totalDebt                77157000000   89260000000   85475000000   86194000000
totalLiabilities                None          None          None          None
totalRevenue             26819000000   28918000000   24538000000   18984000000

## Earnings:

https://www.wallstreetmojo.com/revenue-vs-earnings/

In [9]:
earnings = iex.get_earnings('MSFT')
earnings.T

                                 0           1           2           3
EPSReportDate           2018-04-26  2018-01-31  2017-10-26  2017-07-20
EPSSurpriseDollar              0.1         0.1        0.12        0.27
actualEPS                     0.95        0.96        0.84        0.98
announceTime                   AMC         AMC         AMC         AMC
consensusEPS                  0.85        0.86        0.72        0.71
estimatedChangePercent    0.164384   0.0361446  -0.0526316   0.0289855
estimatedEPS                  0.85        0.86        0.72        0.71
fiscalEndDate           2018-03-31  2017-12-31  2017-09-30  2017-06-30
fiscalPeriod               Q3 2018     Q2 2018     Q1 2018     Q4 2017
numberOfEstimates               14          14          14          14
symbolId                      4563        4563        4563        4563
yearAgo                       0.73        0.83        0.76        0.69
yearAgoChangePercent       0.30137    0.156627    0.105263     0.42029

In [10]:
iex.get_chart('MSFT', chart_range='5y')

,change,changeOverTime,changePercent,close,date,high,label,low,open,unadjustedVolume,volume,vwap
0,0.528641,0.000000,1.744,30.8375,2013-06-17,30.9785,"Jun 17, 13",30.5115,30.5644,49670032,49670032,30.7879
1,-0.017617,-0.000571,-0.057,30.8199,2013-06-18,30.9873,"Jun 18, 13",30.7450,30.8111,28614869,28614869,30.8662
2,-0.343620,-0.011713,-1.115,30.4763,2013-06-19,30.9168,"Jun 19, 13",30.4763,30.8023,30816008,30816008,30.7038
3,-0.969179,-0.043142,-3.180,29.5071,2013-06-20,30.2472,"Jun 20, 13",29.4013,30.1855,54493643,54493643,29.7713
4,-0.198239,-0.049573,-0.672,29.3088,2013-06-21,29.7185,"Jun 21, 13",29.1194,29.6569,85337340,85337340,29.4216
5,0.396482,-0.036715,1.353,29.7053,2013-06-24,30.1326,"Jun 24, 13",28.6965,29.0225,56108988,56108988,29.5549
6,-0.039649,-0.037999,-0.133,29.6657,2013-06-25,30.2912,"Jun 25, 13",29.4806,30.0269,44051085,44051085,29.7243
7,0.599128,-0.018572,2.020,30.2648,2013-06-26,30.3793,"Jun 26, 13",29.8573,30.0621,48665592,48665592,30.2006
8,0.237891,-0.010857,0.786,30.5027,2013-06-27,30.6437,"Jun 27, 13",30.3970,30.4146,28993042,28993042,30.5037
9,-0.066083,-0.013000,-0.217,30.4366,2013-06-28,30.6525,"Jun 28, 13",30.2560,30.2912,65545445,65545445,30.4493
10,-0.162996,-0.018286,-0.536,30.2736,2013-07-01,30.8287,"Jul 1, 13",30.2472,30.6172,31054868,31054868,30.4726
11,-0.370051,-0.030285,-1.222,29.9036,2013-07-02,30.3431,"Jul 2, 13",29.6304,30.3177,37629522,37629522,29.9954
12,0.061674,-0.028287,0.206,29.9652,2013-07-03,30.2824,"Jul 3, 13",29.6040,29.6569,15994380,15994380,29.9691
13,0.176218,-0.022573,0.588,30.1414,2013-07-05,30.1679,"Jul 5, 13",29.5873,30.0357,26085831,26085831,29.9381
14,0.101318,-0.019285,0.336,30.2428,2013-07-08,30.4763,"Jul 8, 13",29.9388,30.2648,32396842,32396842,30.1852
15,0.022029,-0.018572,0.073,30.2648,2013-07-09,30.4851,"Jul 9, 13",30.0798,30.4674,25318501,25318501,30.2804
16,0.308374,-0.008571,1.019,30.5732,2013-07-10,30.6701,"Jul 10, 13",30.2384,30.2560,29863085,29863085,30.5245
17,0.867855,0.019570,2.839,31.4410,2013-07-11,31.5159,"Jul 11, 13",30.7494,30.8375,53618047,53618047,31.2223
18,-0.013214,0.019142,-0.042,31.4278,2013-07-12,31.4807,"Jul 12, 13",31.0842,31.3485,35501154,35501154,31.2991
19,0.440535,0.033427,1.402,31.8683,2013-07-15,31.9124,"Jul 15, 13",31.3485,31.4190,34142125,34142125,31.7347
20,0.088106,0.036287,0.276,31.9565,2013-07-16,32.0973,"Jul 16, 13",31.6833,31.7274,36378481,36378481,31.9205
21,-0.466971,0.021143,-1.461,31.4895,2013-07-17,32.0622,"Jul 17, 13",31.2692,32.0181,37281516,37281516,31.6092
22,-0.264319,0.012572,-0.839,31.2252,2013-07-18,31.6216,"Jul 18, 13",31.0313,31.4719,49118611,49118611,31.0970
23,-3.559500,-0.102859,-11.400,27.6656,2013-07-19,28.7846,"Jul 19, 13",27.3308,28.5467,248354245,248354245,27.1418
24,0.537453,-0.085428,1.943,28.2031,2013-07-22,28.2031,"Jul 22, 13",27.8419,27.9300,79024753,79024753,28.0487
25,-0.167403,-0.090857,-0.594,28.0357,2013-07-23,28.2295,"Jul 23, 13",27.9388,28.1150,65810331,65810331,28.0826
26,0.123349,-0.086859,0.440,28.1590,2013-07-24,28.3617,"Jul 24, 13",28.0974,28.2251,52802180,52802180,28.1918
27,-0.502211,-0.103144,-1.783,27.6568,2013-07-25,27.8859,"Jul 25, 13",27.5335,27.8595,63212927,63212927,27.6685
28,0.202646,-0.096571,0.733,27.8595,2013-07-26,27.8595,"Jul 26, 13",27.4938,27.5423,38633539,38633539,27.6873
29,-0.070485,-0.098857,-0.253,27.7890,2013-07-29,27.8419,"Jul 29, 13",27.6656,27.7273,28873969,28873969,27.7663
...,...,...,...,...,...,...,...,...,...,...,...,...
1230,1.085300,2.072535,1.159,94.7493,2018-05-04,94.9584,"May 4, 18",92.5190,92.9172,22531325,22531325,94.3020
1231,1.055400,2.106760,1.114,95.8047,2018-05-07,96.2926,"May 7, 18",94.6895,94.7592,24242019,24242019,95.7593
1232,-0.408230,2.093522,-0.426,95.3965,2018-05-08,95.7450,"May 8, 18",94.6528,95.4319,23484589,23484589,95.2066
1233,1.125100,2.130007,1.179,96.5216,2018-05-09,96.5515,"May 9, 18",94.6398,95.5956,27327410,27327410,95.8582
1234,0.965813,2.161326,1.001,97.4874,2018-05-10,97.5272,"May 10, 18",96.6311,97.0394,22388119,22388119,97.1801
1235,-0.209093,2.154546,-0.214,97.2783,2018-05-11,97.4476,"May 11, 18",96.6212,97.3779,16778316,16778316,97.0833
1236,0.328576,2.165201,0.338,97.6069,2018-05-14,98.2641,"May 14, 18",96.8900,97.4974,19454124,19454124,97.6669
1237,-0.706936,2.142278,-0.724,96.9000,2018-05-15,97.4277,May 15,95.9242,96.8203,24594010,24594010,96.5606
1238,0.250033,2.150385,0.258,97.1500,2018-05-16,97.4000,May 16,96.6150,97.3600,17384742,17384742,97.0386
1239,-0.970000,2.118930,-0.998,96.1800,2018-05-17,97.5401,May 17,95.8300,96.7600,17246716,17246716,96.5820
1240,0.180000,2.124767,0.187,96.3600,2018-05-18,96.9300,May 18,96.0100,96.0100,17865840,17865840,96.5082
1241,1.240000,2.164978,1.287,97.6000,2018-05-21,98.0100,May 21,96.8000,97.0000,19422467,19422467,97.5232
1242,-0.100000,2.161735,-0.102,97.5000,2018-05-22,98.1700,May 22,97.2000,97.6800,15441189,15441189,97.6037
1243,1.160000,2.199351,1.190,98.6600,2018-05-23,98.7300,May 23,96.3200,96.7100,21251222,21251222,97.8875
1244,-0.350000,2.188002,-0.355,98.3100,2018-05-24,98.9400,May 24,96.8100,98.7250,26649287,26649287,97.9638
1245,0.050000,2.189623,0.051,98.3600,2018-05-25,98.9800,May 25,97.8600,98.3000,18363918,18363918,98.4713
1246,-0.350000,2.178273,-0.356,98.0100,2018-05-29,98.8800,May 29,97.2300,97.8400,28670981,28670981,97.9199
1247,0.940000,2.208756,0.959,98.9500,2018-05-30,99.2500,May 30,97.9100,98.3100,22158528,22158528,98.7044
1248,-0.110000,2.205188,-0.111,98.8400,2018-05-31,99.9900,May 31,98.6100,99.2900,34140891,34140891,99.1149
1249,1.950000,2.268423,1.973,100.7900,2018-06-01,100.8600,Jun 1,99.1700,99.2798,28655624,28655624,100.3299
1250,0.880000,2.296960,0.873,101.6700,2018-06-04,101.8600,Jun 4,100.8510,101.2600,27281623,27281623,101.4561
1251,0.520000,2.313822,0.511,102.1900,2018-06-05,102.3300,Jun 5,101.5300,102.0000,23514402,23514402,102.0279
1252,0.300000,2.323551,0.294,102.4900,2018-06-06,102.6000,Jun 6,101.9000,102.4800,21122917,21122917,102.3375
1253,-1.610000,2.271342,-1.571,100.8800,2018-06-07,102.6900,Jun 7,100.3800,102.6500,28232197,28232197,101.2007
1254,0.750000,2.295663,0.743,101.6300,2018-06-08,101.9500,Jun 8,100.5400,101.0924,22165128,22165128,101.3673
1255,-0.580000,2.276854,-0.571,101.0500,2018-06-11,101.5900,Jun 11,100.6700,101.3700,23490894,23490894,101.1346
1256,0.260000,2.285286,0.257,101.3100,2018-06-12,101.4493,Jun 12,100.7500,101.1000,18325228,18325228,101.1775
1257,-0.460000,2.270369,-0.454,100.8500,2018-06-13,102.0100,Jun 13,100.5600,101.7200,29492875,29492875,101.1961
1258,0.570000,2.288853,0.565,101.4200,2018-06-14,102.0300,Jun 14,101.0000,101.6500,25691811,25691811,101.4732
1259,-1.290000,2.247021,-1.272,100.1300,2018-06-15,101.5300,Jun 15,100.0700,101.5100,65738585,65738585,100.6170

## Getting a Quote:

In [14]:
print(iex.get_delayed_quote('MSFT'))
iex.get_quote('MSFT')

{'symbol': 'GOOGL', 'delayedPrice': 1159.27, 'high': 1163.909, 'low': 1153.69, 'delayedSize': 356727, 'delayedPriceTime': 1529092800490, 'processedTime': 1529093701006}

{'symbol': 'GOOGL',
 'companyName': 'Alphabet Inc.',
 'primaryExchange': 'Nasdaq Global Select',
 'sector': 'Technology',
 'calculationPrice': 'close',
 'open': 1159.92,
 'openTime': 1529069400741,
 'close': 1159.27,
 'closeTime': 1529092800490,
 'high': 1163.909,
 'low': 1153.69,
 'latestPrice': 1159.27,
 'latestSource': 'Close',
 'latestTime': 'June 15, 2018',
 'latestUpdate': 1529092800490,
 'latestVolume': 2162151,
 'iexRealtimePrice': 1159.25,
 'iexRealtimeSize': 100,
 'iexLastUpdated': 1529092799901,
 'delayedPrice': 1159.27,
 'delayedPriceTime': 1529092800490,
 'extendedPrice': 1159.3,
 'extendedChange': 0.03,
 'extendedChangePercent': 3e-05,
 'extendedPriceTime': 1529096370987,
 'previousClose': 1160.11,
 'change': -0.84,
 'changePercent': -0.00072,
 'iexMarketPercent': 0.02185,
 'iexVolume': 47243,
 'avgTotalVolume': 1717417,
 'iexBidPrice': 0,
 'iexBidSize': 0,
 'iexAskPrice': 0,
 'iexAskSize': 0,
 'marketCap': 805169544483,
 'peRatio': 33.89,
 'week52High': 1198,
 'week52Low': 915.31,
 'ytdChange': 0.08025203715954926}

In [15]:
iex.get_effective_spread('MSFT')

,effectiveQuoted,effectiveSpread,priceImprovement,venue,venueName,volume
0,0.839796,0.475473,0.052364,XCHI,CHX,36654
1,0.725551,0.354695,0.084232,XPHL,Nasdaq PSX,423955
2,0.880346,0.316727,0.033251,XASE,NYSE American,64715
3,0.753807,0.304354,0.075636,XNYS,NYSE,123166
4,0.645739,0.304035,0.098014,BATY,Cboe BYX,752568
5,0.681487,0.299712,0.092928,XNGS,Nasdaq,8228998
6,0.699947,0.297866,0.092912,XBOS,Nasdaq BX,746780
7,0.969739,0.294594,0.010330,XCIS,NYSE National,4330
8,0.627604,0.290454,0.108699,BATS,Cboe BZX,2309731
9,0.712717,0.282923,0.081141,ARCX,NYSE Arca,1856462
10,0.618326,0.278203,0.105503,EDGA,Cboe EDGA,329973
11,0.669492,0.275934,0.097082,EDGX,Cboe EDGX,2522837
12,0.461428,0.211759,0.147064,IEXG,IEX,1043850

## Stats:

In [16]:
iex.get_stats('GOOGL').T

                                 0
EBITDA                 25870000000
EPSSurpriseDollar             None
EPSSurprisePercent          7.8176
beta                       1.08347
cash                  296727000000
companyName          Alphabet Inc.
consensusEPS                  9.21
day200MovingAvg            1057.38
day30ChangePercent        0.103016
day50MovingAvg             1079.96
day5ChangePercent        0.0161013
debt                             0
dividendRate                     0
dividendYield                    0
exDividendDate                   0
float                    673923008
grossProfit            50317000000
insiderPercent                None
institutionPercent            29.7
latestEPS                        0
latestEPSDate           2017-12-31
marketcap             805169544483
month1ChangePercent      0.0685796
month3ChangePercent     0.00752644
month6ChangePercent      0.0814086
numberOfEstimates               13
peRatioHigh                      0
peRatioLow                       0
priceToBook                   None
priceToSales               7.34861
profitMargin                 14.81
returnOnAssets                8.18
returnOnCapital               None
returnOnEquity               10.13
revenue                86105000000
revenuePerEmployee         1012404
revenuePerShare                124
sharesOutstanding        694548763
shortDate               2018-05-31
shortInterest              3159592
shortRatio                 1.88123
symbol                       GOOGL
ttmEPS                       34.21
week52change               20.7347
week52high                    1198
week52low                   915.31
year1ChangePercent        0.207347
year2ChangePercent        0.583291
year5ChangePercent         1.61351
ytdChangePercent         0.0801893