# Goldman Sachs (GS):

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import quandl

import iex as IEX

from iexfinance import Stock
from iexfinance import get_historical_data
from iexfinance import get_stats_intraday

from datetime import datetime

quandl.ApiConfig.api_key = "9tQnPMV9zakeCm4K6S5X"

In [2]:
! ls data

EOD-datasets-codes.csv facebook_quandle.csv   jpm_quandle.csv
apple_quandle.csv      google_quandle.csv     microsoft_quandle.csv
blackrock_quandle.csv  gs_quandle.csv         moodys_quandle.csv
dow_quandle.csv        ibm_quandle.csv        twitter_quandle.csv

## Importing Stock History - Goldman Sachs:

- **From Quadle**

In [3]:
df = pd.read_csv('data/gs_quandle.csv')
df.head()

,Date,WIKI/GS - Open,WIKI/GS - High,WIKI/GS - Low,WIKI/GS - Close,WIKI/GS - Volume,WIKI/GS - Ex-Dividend,WIKI/GS - Split Ratio,WIKI/GS - Adj. Open,WIKI/GS - Adj. High,WIKI/GS - Adj. Low,WIKI/GS - Adj. Close,WIKI/GS - Adj. Volume
0,1999-05-04,76.00,77.25,70.00,70.38,22320900.0,0.0,1.0,63.037666,64.074470,58.061009,58.376197,22320900.0
1,1999-05-05,69.88,69.88,66.25,69.13,7565700.0,0.0,1.0,57.961475,57.961475,54.950597,57.339393,7565700.0
2,1999-05-06,68.00,69.38,67.06,67.94,2905700.0,0.0,1.0,56.402123,57.546754,55.622446,56.352356,2905700.0
3,1999-05-07,67.94,74.88,66.75,74.13,4862300.0,0.0,1.0,56.352356,62.108690,55.365319,61.486608,4862300.0
4,1999-05-10,73.38,73.50,70.25,70.69,2589400.0,0.0,1.0,60.864526,60.964059,58.268369,58.633324,2589400.0

-------

## Querying IEX for Goldman Sachs's Stock:

In [4]:
goldman = Stock('GS')

In [5]:
print('Current Price:', goldman.get_price())
print('06/15/2018 Opening Price:', goldman.get_open())
print('06/15/2018 Closing Price:', goldman.get_close())

Current Price: 231.92
06/15/2018 Opening Price: 230.97
06/15/2018 Closing Price: 231.92

## Historical Data from IEX:

In [7]:
start = datetime(2013, 1, 1) ## 5 year limit:
end = datetime(2018, 6, 15) ## Today's Date

goldman_df = get_historical_data("GS", start=start, end=end, output_format='pandas')
goldman_df.head(10)

                open      high       low     close   volume
date
2013-06-17  153.4483  154.9352  152.3494  153.4763  2628240
2013-06-18  153.5137  154.1870  152.4850  153.5137  2059734
2013-06-19  153.5231  154.2432  151.0448  151.0916  3554203
2013-06-20  148.8377  149.6233  144.8070  145.3401  6488769
2013-06-21  146.8270  147.0702  142.4316  144.2552  5390489
2013-06-24  142.1416  142.7121  139.0742  141.0101  4012960
2013-06-25  142.5719  144.3113  141.7302  143.1423  3274809
2013-06-26  144.4703  144.5451  140.9820  141.8330  3580307
2013-06-27  143.1143  144.9473  142.7215  143.5632  2654849
2013-06-28  142.7963  142.8711  141.2158  141.4496  3013155

## Financial Statement:

In [8]:
iex = IEX.Stock()
financials = iex.get_financials('GS')
financials.T

                                   0             1             2             3
cashChange               10452000000   -6559000000    5722000000  -12147000000
cashFlow                  -964000000   -6623000000    2734000000  -10464000000
costOfRevenue                   None          None          None          None
currentAssets                   None          None          None          None
currentCash             120503000000  110051000000  116610000000  110888000000
currentDebt              47760000000   46922000000   45357000000   42966000000
grossProfit                     None          None          None          None
netIncome                 2832000000   -1928000000    2128000000    1831000000
operatingExpense                None          None          None          None
operatingGainsLosses             NaN        -6e+06           NaN           NaN
operatingIncome                 None          None          None          None
operatingRevenue                None          None          None          None
reportDate                2018-03-31    2017-12-31    2017-09-30    2017-06-30
researchAndDevelopment          None          None          None          None
shareholderEquity        83579000000   82243000000   86292000000   86675000000
totalAssets             973535000000  916776000000  930132000000  906518000000
totalCash                       None          None          None          None
totalDebt               300416000000  289397000000  279948000000  269046000000
totalLiabilities                None          None          None          None
totalRevenue             10036000000    7834000000    8326000000    7887000000

## Earnings:

https://www.wallstreetmojo.com/revenue-vs-earnings/

In [9]:
earnings = iex.get_earnings('GS')
earnings.T

                                 0           1           2           3
EPSReportDate           2018-04-17  2018-01-17  2017-10-17  2017-07-18
EPSSurpriseDollar             1.28        0.78        0.71        0.59
actualEPS                     6.95        5.68        5.02        3.95
announceTime                   BTO         BTO         BTO         BTO
consensusEPS                  5.67         4.9        4.31        3.36
estimatedChangePercent    0.100971  -0.0354331   -0.116803  -0.0967742
estimatedEPS                  5.67         4.9        4.31        3.36
fiscalEndDate           2018-03-31  2017-12-31  2017-09-30  2017-06-30
fiscalPeriod               Q1 2018     Q4 2017     Q3 2017     Q2 2017
numberOfEstimates                6           6           7           5
symbolId                      3004        3004        3004        3004
yearAgo                       5.15        5.08        4.88        3.72
yearAgoChangePercent      0.349515     0.11811   0.0286885    0.061828

In [10]:
iex.get_chart('GS', chart_range='5y')

,change,changeOverTime,changePercent,close,date,high,label,low,open,unadjustedVolume,volume,vwap
0,1.112900,0.000000,0.730,153.4763,2013-06-17,154.9352,"Jun 17, 13",152.3494,153.4483,2628240,2628240,153.6242
1,0.037407,0.000244,0.024,153.5137,2013-06-18,154.1870,"Jun 18, 13",152.4850,153.5137,2059734,2059734,153.4075
2,-2.422200,-0.015538,-1.578,151.0916,2013-06-19,154.2432,"Jun 19, 13",151.0448,153.5231,3554203,3554203,152.3917
3,-5.751500,-0.053013,-3.807,145.3401,2013-06-20,149.6233,"Jun 20, 13",144.8070,148.8377,6488769,6488769,146.8432
4,-1.084800,-0.060082,-0.746,144.2552,2013-06-21,147.0702,"Jun 21, 13",142.4316,146.8270,5390489,5390489,144.5360
5,-3.245200,-0.081226,-2.250,141.0101,2013-06-24,142.7121,"Jun 24, 13",139.0742,142.1416,4012960,4012960,140.7929
6,2.132300,-0.067333,1.512,143.1423,2013-06-25,144.3113,"Jun 25, 13",141.7302,142.5719,3274809,3274809,143.0374
7,-1.309300,-0.075864,-0.915,141.8330,2013-06-26,144.5451,"Jun 26, 13",140.9820,144.4703,3580307,3580307,142.2156
8,1.730100,-0.064590,1.220,143.5632,2013-06-27,144.9473,"Jun 27, 13",142.7215,143.1143,2654849,2654849,143.9926
9,-2.113600,-0.078362,-1.472,141.4496,2013-06-28,142.8711,"Jun 28, 13",141.2158,142.7963,3013155,3013155,141.8639
10,0.467606,-0.075315,0.331,141.9172,2013-07-01,144.1149,"Jul 1, 13",141.8704,142.8805,2494163,2494163,143.0400
11,-0.776221,-0.080373,-0.547,141.1410,2013-07-02,143.2639,"Jul 2, 13",140.1871,141.3654,3091265,3091265,141.6100
12,-0.458249,-0.083359,-0.325,140.6827,2013-07-03,141.6086,"Jul 3, 13",139.6073,139.9252,1270376,1270376,140.6383
13,2.627900,-0.066236,1.868,143.3107,2013-07-05,143.3574,"Jul 5, 13",141.6834,142.4316,2243650,2243650,142.5851
14,0.533064,-0.062763,0.372,143.8437,2013-07-08,144.7696,"Jul 8, 13",142.9740,144.5638,2700264,2700264,143.9574
15,2.927200,-0.043690,2.035,146.7709,2013-07-09,147.2385,"Jul 9, 13",143.2452,144.9473,3128249,3128249,145.6461
16,-1.038100,-0.050454,-0.707,145.7328,2013-07-10,147.4092,"Jul 10, 13",144.6480,146.4249,2445210,2445210,145.6705
17,1.758200,-0.038998,1.206,147.4910,2013-07-11,149.3895,"Jul 11, 13",145.9947,148.2298,2966333,2966333,147.2146
18,2.244500,-0.024374,1.522,149.7355,2013-07-12,149.8945,"Jul 12, 13",148.2813,148.3421,2844627,2844627,149.2106
19,2.702700,-0.006763,1.805,152.4383,2013-07-15,152.8030,"Jul 15, 13",150.7175,152.2512,4129976,4129976,151.9877
20,-2.581200,-0.023581,-1.693,149.8571,2013-07-16,153.6540,"Jul 16, 13",149.0996,153.2986,5972427,5972427,151.1373
21,1.178400,-0.015904,0.786,151.0354,2013-07-17,151.4937,"Jul 17, 13",149.1650,149.4830,3715484,3715484,150.6535
22,2.394100,-0.000304,1.585,153.4296,2013-07-18,153.9159,"Jul 18, 13",151.0354,151.1103,3461828,3461828,153.0518
23,0.280560,0.001523,0.183,153.7101,2013-07-19,154.1684,"Jul 19, 13",152.0455,153.1397,3329695,3329695,153.4259
24,1.767500,0.013040,1.150,155.4777,2013-07-22,155.5525,"Jul 22, 13",153.2612,153.3267,2741316,2741316,154.8594
25,0.009353,0.013101,0.006,155.4870,2013-07-23,156.5625,"Jul 23, 13",154.7576,155.7115,2545591,2545591,155.4928
26,-1.140900,0.005667,-0.734,154.3461,2013-07-24,156.0762,"Jul 24, 13",153.7849,155.9453,2546792,2546792,154.3990
27,0.813626,0.010968,0.527,155.1597,2013-07-25,155.2439,"Jul 25, 13",153.0835,153.6353,2235168,2235168,154.4653
28,-0.607884,0.007008,-0.392,154.5518,2013-07-26,154.9165,"Jul 26, 13",153.6260,154.3554,2372436,2372436,154.3944
29,-1.954600,-0.005728,-1.265,152.5972,2013-07-29,154.1459,"Jul 29, 13",151.5218,153.9626,2824153,2824153,152.6369
...,...,...,...,...,...,...,...,...,...,...,...,...
1230,1.524600,0.525396,0.655,234.1121,2018-05-04,235.9556,"May 4, 18",231.4614,231.4913,2622252,2622252,234.3153
1231,2.252000,0.540069,0.962,236.3641,2018-05-07,237.3306,"May 7, 18",234.4459,235.1683,1979446,1979446,236.2060
1232,-0.199295,0.538770,-0.084,236.1648,2018-05-08,239.8119,"May 8, 18",235.1683,237.4004,3267002,3267002,237.2753
1233,4.713300,0.569481,1.996,240.8781,2018-05-09,241.1970,"May 9, 18",236.4119,237.1414,2434002,2434002,239.3847
1234,1.704000,0.580583,0.707,242.5821,2018-05-10,244.5551,"May 10, 18",239.3181,241.2568,2598955,2598955,242.5486
1235,-0.518167,0.577208,-0.214,242.0640,2018-05-11,244.0469,"May 11, 18",240.8582,242.5821,1540146,1540146,242.3108
1236,0.986511,0.583635,0.408,243.0505,2018-05-14,245.0135,"May 14, 18",242.6419,242.7416,1928526,1928526,243.8023
1237,-2.341700,0.568377,-0.963,240.7087,2018-05-15,243.0903,May 15,239.8219,242.1437,2165705,2165705,241.2497
1238,-0.597886,0.564482,-0.248,240.1109,2018-05-16,240.9878,May 16,239.7422,240.4198,1965177,1965177,240.3943
1239,-1.853400,0.552405,-0.772,238.2574,2018-05-17,241.5856,May 17,237.9385,239.5728,2462688,2462688,239.3174
1240,-2.092600,0.538770,-0.878,236.1648,2018-05-18,237.8987,May 18,236.0353,237.2609,2698990,2698990,236.7635
1241,0.697533,0.543315,0.295,236.8623,2018-05-21,239.2240,May 21,236.4837,238.2574,1951741,1951741,237.6405
1242,0.298943,0.545263,0.126,237.1613,2018-05-22,239.8508,May 22,237.1414,237.8588,2551478,2551478,238.4619
1243,-0.189330,0.544030,-0.080,236.9720,2018-05-23,237.0317,May 23,233.5540,236.0452,3114002,3114002,235.5005
1244,-1.704000,0.532927,-0.719,235.2680,2018-05-24,236.3342,May 24,232.8266,235.7662,2308658,2308658,234.8775
1245,-1.086200,0.525850,-0.462,234.1818,2018-05-25,235.2879,May 25,233.4544,234.1719,1985610,1985610,234.2604
1246,-7.951900,0.474038,-3.396,226.2299,2018-05-29,231.6508,May 29,224.2270,230.7041,5323609,5323609,227.0299
1247,2.930100,0.493130,1.295,229.1600,2018-05-30,229.6660,May 30,226.2800,228.9400,3348589,3348589,228.4530
1248,-3.280000,0.471758,-1.431,225.8800,2018-05-31,228.1100,May 31,224.0900,227.3400,5334873,5334873,225.4978
1249,2.470000,0.487852,1.094,228.3500,2018-06-01,230.2500,Jun 1,228.0900,228.4000,3330852,3330852,229.0298
1250,1.540000,0.497886,0.674,229.8900,2018-06-04,231.1500,Jun 4,228.9500,230.3500,2133594,2133594,229.8512
1251,-1.550000,0.487787,-0.674,228.3400,2018-06-05,229.3400,Jun 5,227.2900,228.9400,1986219,1986219,228.4069
1252,3.890000,0.513133,1.704,232.2300,2018-06-06,232.5800,Jun 6,229.3600,229.8500,2566410,2566410,231.4094
1253,1.220000,0.521082,0.525,233.4500,2018-06-07,235.9200,Jun 7,232.5400,233.8900,2904959,2904959,234.1407
1254,-0.060000,0.520691,-0.026,233.3900,2018-06-08,234.2699,Jun 8,232.3500,233.0000,2253128,2253128,233.3856
1255,0.700000,0.525252,0.300,234.0900,2018-06-11,235.1600,Jun 11,233.5850,234.6200,1936809,1936809,234.3629
1256,-1.460000,0.515739,-0.624,232.6300,2018-06-12,235.2300,Jun 12,231.8600,234.1200,2079981,2079981,233.0390
1257,1.200000,0.523558,0.516,233.8300,2018-06-13,238.2300,Jun 13,233.1000,233.6500,3637425,3637425,235.0398
1258,-0.180000,0.522385,-0.077,233.6500,2018-06-14,235.8900,Jun 14,232.5900,235.8700,2899565,2899565,233.6901
1259,-1.730000,0.511113,-0.740,231.9200,2018-06-15,233.1500,Jun 15,229.8400,231.5000,4738084,4738084,231.4536

## Getting a Quote:

In [11]:
print(iex.get_delayed_quote('GS'))
iex.get_quote('GS')

{'symbol': 'GS', 'delayedPrice': 231.92, 'high': 233.15, 'low': 229.84, 'delayedSize': 620361, 'delayedPriceTime': 1529092918341, 'processedTime': 1529093819530}

{'symbol': 'GS',
 'companyName': 'Goldman Sachs Group Inc. (The)',
 'primaryExchange': 'New York Stock Exchange',
 'sector': 'Financial Services',
 'calculationPrice': 'close',
 'open': 230.97,
 'openTime': 1529069474508,
 'close': 231.92,
 'closeTime': 1529092918341,
 'high': 233.15,
 'low': 229.84,
 'latestPrice': 231.92,
 'latestSource': 'Close',
 'latestTime': 'June 15, 2018',
 'latestUpdate': 1529092918341,
 'latestVolume': 4666857,
 'iexRealtimePrice': 231.94,
 'iexRealtimeSize': 100,
 'iexLastUpdated': 1529092795338,
 'delayedPrice': 231.92,
 'delayedPriceTime': 1529092918341,
 'extendedPrice': 231.5,
 'extendedChange': -0.42,
 'extendedChangePercent': -0.00181,
 'extendedPriceTime': 1529096030874,
 'previousClose': 233.65,
 'change': -1.73,
 'changePercent': -0.0074,
 'iexMarketPercent': 0.01225,
 'iexVolume': 57169,
 'avgTotalVolume': 2727203,
 'iexBidPrice': 0,
 'iexBidSize': 0,
 'iexAskPrice': 0,
 'iexAskSize': 0,
 'marketCap': 87600378737,
 'peRatio': 10.74,
 'week52High': 275.31,
 'week52Low': 214.64,
 'ytdChange': -0.08772051213925755}

In [12]:
iex.get_effective_spread('GS')

,effectiveQuoted,effectiveSpread,priceImprovement,venue,venueName,volume
0,0.631347,0.053163,0.014289,XCHI,CHX,9996
1,0.753536,0.042525,0.008091,BATY,Cboe BYX,1234545
2,0.750576,0.041396,0.007868,XBOS,Nasdaq BX,1911562
3,0.665382,0.039221,0.011274,BATS,Cboe BZX,5384494
4,0.644689,0.039186,0.012266,XPHL,Nasdaq PSX,267038
5,0.721086,0.037745,0.008596,XNYS,NYSE,8080839
6,0.701846,0.037678,0.009506,ARCX,NYSE Arca,3123374
7,0.651590,0.036900,0.006773,XCIS,NYSE National,629
8,0.748588,0.036880,0.008057,EDGA,Cboe EDGA,386856
9,0.675634,0.033505,0.010110,EDGX,Cboe EDGX,3608301
10,0.610602,0.031154,0.011553,XNGS,Nasdaq,7377172
11,0.678333,0.026934,0.011036,XASE,NYSE American,86383
12,0.336840,0.017644,0.020243,IEXG,IEX,1374956

## Stats:

In [13]:
iex.get_stats('GS').T

                                                  0
EBITDA                                            0
EPSSurpriseDollar                              None
EPSSurprisePercent                           22.575
beta                                        1.30865
cash                                              0
companyName          Goldman Sachs Group Inc. (The)
consensusEPS                                   5.67
day200MovingAvg                             245.104
day30ChangePercent                      -0.00936346
day50MovingAvg                              239.521
day5ChangePercent                       -0.00926994
debt                                   548994000000
dividendRate                                    3.2
dividendYield                               1.37979
exDividendDate                2018-05-30 00:00:00.0
float                                     359648733
grossProfit                                       0
insiderPercent                                 None
institutionPercent                               65
latestEPS                                      9.02
latestEPSDate                            2017-12-31
marketcap                               87600378737
month1ChangePercent                      -0.0365118
month3ChangePercent                       -0.127039
month6ChangePercent                      -0.0924548
numberOfEstimates                                 6
peRatioHigh                                      21
peRatioLow                                        0
priceToBook                                    1.21
priceToSales                                1.94623
profitMargin                                  10.47
returnOnAssets                                 0.42
returnOnCapital                                None
returnOnEquity                                 5.33
revenue                                 24047000000
revenuePerEmployee                           644692
revenuePerShare                                  64
sharesOutstanding                         377718087
shortDate                                2018-05-31
shortInterest                               5181912
shortRatio                                  1.81962
symbol                                           GS
ttmEPS                                         21.6
week52change                                 5.2397
week52high                                   275.31
week52low                                    214.64
year1ChangePercent                        0.0523975
year2ChangePercent                         0.628305
year5ChangePercent                         0.511113
ytdChangePercent                           -0.08713